import React from "react";

import ProgressBar from "@ramonak/react-progress-bar";

import Section from "../../components/edit/Section";
import Card from "../../components/edit/Card";
import MindMap from "../../components/edit/MindMap";

/*
{
  id: 'root',
  topic: 'Topic',
  date: new Date(),
  children: [
    {
      'id': 'a uuid, generated by mind map',
      'topic': 'A string contains the item',
      children: [
        {
          // id, topic, children, date
        }
      ],
      date: new Date(),
    }
  ]
}
*/
const defaultData = {
  id: "root",
  topic: "Enter your topic here",
  children: [],
};

class EditPage extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      data: defaultData,
    };
  }

  componentDidMount() {
    this.loadProject();
  }

  render() {
    return (
      <div>
        <Card>
          <ProgressBar completed={60} />
          <Section data={this.state.data} key={this.state.data.id} />
        </Card>
        <Card>
          <MindMap
            data={this.state.data}
            onMapChange={this.onMapChange.bind(this)}
          />
        </Card>
      </div>
    );
  }

  loadProject() {
    console.log("loading project");
    const localData = localStorage.getItem("current_project");
    const data = localData ? JSON.parse(localData) : defaultData;

    this.setState({ data });
  }

  onMapChange(data) {
    this.setState({ data });
    localStorage.setItem("current_project", JSON.stringify(data));
  }
}

export default EditPage;
