import React from "react";
import Section from "../../components/edit/Section";
import Card from "../../components/edit/Card";
import MindMap from "../../components/edit/MindMap";

const dummy = {
  name: "TooooDooooo",
  style: "category",
  "Assignment 1": {
    name: "Assignment 1",
    style: "category",
    Algorithms: {
      name: "Algorithms",
      style: "subcategory",
      Algorithms1: {
        name: "Dijkstra",
        style: "list",
      },
      Algorithms2: {
        name: "Prim",
        style: "list",
      },
      Algorithms3: {
        name: "BFS",
        style: "list",
      },
    },
  },
  "Assignment 2": {
    name: "Assignment 2",
    style: "category",
    Algorithms: {
      name: "Algorithms",
      style: "subcategory",
      Algorithms1: {
        name: "Support Vector Machine",
        style: "list",
      },
      Algorithms2: {
        name: "RNN",
        style: "list",
      },
      Algorithms3: {
        name: "DFS",
        style: "list",
      },
    },
  },
};

/*
{
  id: 'root',
  topic: 'Topic',
  date: new Date(),
  children: [
    {
      'id': 'a uuid, generated by mind map',
      'topic': 'A string contains the item',
      children: [
        {
          // id, topic, children, date
        }
      ],
      date: new Date(),
    }
  ]
}
*/
const defaultData = {
  id: "root",
  topic: "Enter your topic here",
  children: [],
};

class EditPage extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      data: defaultData,
    };
  }

  componentDidMount() {
    this.loadProject();
  }

  render() {
    return (
      <div>
        <Card>
          <Section category={dummy} key={dummy.name} />
        </Card>
        <Card>
          <MindMap
            data={this.state.data}
            onMapChange={this.onMapChange.bind(this)}
          />
        </Card>
      </div>
    );
  }

  loadProject() {
    console.log("loading project");
    const localData = localStorage.getItem("current_project");
    const data = localData ? JSON.parse(localData) : defaultData;

    this.setState({ data });
  }

  onMapChange(data) {
    this.setState({ data });
    localStorage.setItem("current_project", JSON.stringify(data));
  }
}

export default EditPage;
